- name: Partition disk
  community.general.parted:
    name: "data"
    device: "/dev/vdb"
    label: "gpt"
    number: 1
    state: present
    fs_type: xfs
  become: true
  become_user: root
- name: Format disk
  community.general.filesystem:
    dev: "/dev/vdb1"
    fstype: "xfs"
    state: present
  become: true
  become_user: root
- name: Make mount point
  ansible.builtin.file:
    path: /data
    state: directory
  become: true
  become_user: root
- name: XFS mount
  ansible.posix.mount:
    boot: true
    state: mounted
    fstype: xfs
    src: "/dev/vdb1"
    path: /data
    opts: defaults
  become: true
  become_user: root

