---
- name: Install yum packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
  become: true
  vars:
    packages:
      - java-1.8.0-openjdk
- name: Install pip packages
  ansible.builtin.pip:
    name: lxml
  become: true
- name: Create folder for hive
  ansible.builtin.file:
    path: "{{ hive_install_path }}"
    state: directory
  become: true
- name: Fetch the Hive distribution
  ansible.builtin.unarchive:
    src: https://repo1.maven.org/maven2/org/apache/hive/hive-standalone-metastore/3.1.3/hive-standalone-metastore-3.1.3-bin.tar.gz
    dest: "{{ hive_install_path }}"
    remote_src: true
    creates: "{{ hive_path }}" # Idempotency
  become: true
- name: Pass the serivice config template
  ansible.builtin.template:
    src: hive.service
    dest: /etc/systemd/system
  become: true
  notify:
    - Restart Hive
    - Restart Trino
- name: Just force systemd to reread configs (2.4 and above)
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true
- name: Link Jars from Hadoop to Hive
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  become: true
  loop:
    - src: "{{ hadoop_path }}/share/hadoop/tools/lib/aws-java-sdk-bundle-1.12.367.jar"
      dest: "{{ hive_path }}/lib/aws-java-sdk-bundle-1.12.367.jar"
    - src: "{{ hadoop_path }}/share/hadoop/tools/lib/hadoop-aws-3.3.6.jar"
      dest: "{{ hive_path }}/lib/hadoop-aws-3.3.6.jar"
#  src: "{{hadoop_path}}/share/hadoop/common/lib/guava-27.0-jre.jar"
#  dest: "{{hive_path}}/lib/guava-27.0-jre.jar"
- name: Pass the configuration templates
  ansible.builtin.template:
    src: metastore-site.xml
    dest: "{{ hive_path }}/conf/metastore-site.xml"
  become: true
  notify:
    - Restart Hive
    - Restart Trino
- name: Configure the Hive management DB
  ansible.builtin.command: "{{ hive_path }}/bin/schematool -dbType derby -initSchema"
  environment: "{{ hadoop_env }}"
  args:
    chdir: "{{ hive_path }}"
    creates: "{{ hive_path }}/metastore_db"
  become: true
