- name: Install pip packages
  ansible.builtin.pip:
    name: lxml
  become: true
- name: Create folder for hive
  ansible.builtin.file:
    path: "{{ hive_install_path }}"
    state: directory
  become: true
- name: Fetch the Hive distribution
  ansible.builtin.unarchive:
    src: https://repo1.maven.org/maven2/org/apache/hive/hive-standalone-metastore/4.0.1/hive-standalone-metastore-4.0.1-bin.tar.gz
    dest: "{{ hive_install_path }}"
    remote_src: true
    creates: "{{ hive_path }}" # Idempotency
  become: true
- name: Pass the serivice config template
  ansible.builtin.template:
    src: hive.service
    dest: /etc/systemd/system
  become: true
  notify:
    - Restart Hive
#    - Restart Trino
- name: Just force systemd to reread configs (2.4 and above)
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true
- name: Link Jars from Hadoop to Hive
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  become: true
  loop:
    - src: "/home/almalinux/hadoop-3.4.1/share/hadoop/tools/lib/bundle-2.24.6.jar"
      dest: "{{ hive_path }}/lib/bundle-2.24.6.jar"
    - src: "/home/almalinux/hadoop-3.4.1/share/hadoop/tools/lib/hadoop-aws-3.4.1.jar"
      dest: "{{ hive_path }}/lib/hadoop-aws-3.4.1.jar"