- name: Set up primary node for replication
  hosts: replicas
  tasks: 
  - name: Stop postgresql
    ansible.builtin.service: 
      name: postgresql 
      state: stopped
    become: true
  - name: Clear out DB folder
    ansible.builtin.file:
      state: absent
      path: /var/lib/pgsql/data
    become: true
    become_user: postgres
  - name: Snapshot primary
    ansible.builtin.shell: "PGPASSWORD={{lookup('ansible.builtin.password', './.replicatorpass', length=16) }} pg_basebackup -h {{groups['primary_node'][0]}} -U replicator -D /var/lib/pgsql/data -Fp -Xs -P"
    become: true
    become_user: postgres
  - name: Enable replication
    ansible.builtin.blockinfile:
      path: "/var/lib/pgsql/data/postgresql.conf"
      block: |
        primary_conninfo = 'host={{groups["primary_node"][0]}} port=5432 user=replicator password={{lookup("ansible.builtin.password", "./.replicatorpass", length=16) }}'
        ssl = on
        ssl_cert_file = 'server.crt'
        ssl_key_file = 'server.key'
    become: true
    become_user: postgres 
  - name: Start postgresql
    ansible.builtin.service: 
      name: postgresql 
      state: started
    become: true