#cloud-config
bootcmd:
  - [ cloud-init-per, once, "dnf install -y firewalld" ]
  - [ cloud-init-per, once, "nmcli con mod 'System eth0' +ipv4.addresses '192.168.68.1/24'"]
  - [ cloud-init-per, once, "nmcli con down 'System eth0'"]
  - [ cloud-init-per, once, "nmcli con up 'System eth0'"]
  - [ cloud-init-per, once, "systemctl enable --now firewalld"]
  - [ cloud-init-per, once, "echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf"]
  - [ cloud-init-per, once, "sysctl -p" ]
  - [ cloud-init-per, once, "firewall-cmd --zone=public --add-forward" ]
  - [ cloud-init-per, once, "firewall-cmd --zone=public --add-rich-rule='rule family=ipv4 source address=192.168.68.0/24 masquerade'" ]
  - [ cloud-init-per, once, "dnf config-manager --set-enabled crb" ]
  - [ cloud-init-per, once, "dnf install -y, epel-release" ]

ssh_authorized_keys:
  - ${public_key_openssh}
