#cloud-config
bootcmd:
  - [ dnf, config-manager, --set-enabled, crb ]
  - [ dnf, install, -y, epel-release ]
  - [ echo, ${gateway} ]
  - [ echo, ${host_ip}]

ssh_authorized_keys:
  - ${public_key_openssh}
