- name: Set up DNS on nodes
  hosts: nodes
  become: true
  become_user: root
  tasks: 
  - name: Set local DNS server
    ansible.builtin.shell: "nmcli con mod 'System eth0' ipv4.dns '192.168.51.1'"
  - name: Restart interface
    ansible.builtin.shell: "nmcli con down 'System eth0' && nmcli con up 'System eth0'"