#cloud-config
package_reboot_if_required: true
package_update: true
package_upgrade: true

bootcmd:
  - [ dnf, config-manager, --set-enabled, crb ]
  - [ dnf, install, -y, epel-release ]

yum_repos:
  docker-ce-stable:
    name: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: true 
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
  
packages:
  - screen
  - tmux
  - nano
  - vim
  - bind-utils
  - net-tools
  - git
  - htop
  - python3-pip
  - python3-virtualenv
  - python3-devel
  - ansible
  - docker-ce 
  - docker-ce-cli 
  - containerd.io 
  - docker-buildx-plugin
  - docker-compose-plugin


runcmd:
  - [ systemctl, enable, --now, docker ]
  - [ usermod, -a, -G, docker, almalinux ]

ssh_authorized_keys:
  - ${public_key_openssh}
