- name: Install Docker tools
  hosts: all
  become: true
  become_user: root
  tasks: 
  - name: Install iptables-nft
    ansible.builtin.dnf:
      name:
        - iptables-nft
      state: latest
  - name: Install Docker
    ansible.builtin.dnf:
      name:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin
        - docker-compose-plugin
      state: latest
  - name: Set up mirror registry
    ansible.builtin.copy:
      dest: /etc/docker/daemon.json
      src: ./files/daemon.json
  - name: Ensure certificate directory
    ansible.builtin.file:
      path: /etc/docker/certs.d
      state: directory
  - name: Create directory for cache certificate
    ansible.builtin.file:
      path: "/etc/docker/certs.d/10.134.12.37:4000"
      state: directory
  - name: Install cache certificate
    ansible.builtin.copy:
      dest: "/etc/docker/certs.d/10.134.12.37:4000/ca.crt"
      src: ./files/tls.crt
  - name: Enable Docker Service
    ansible.builtin.service:
      name: docker
      enabled: true
      state: started
  - name: Add almalinux to the docker group
    ansible.builtin.user:
      append: true
      groups: docker
      name: almalinux
