- name: Install Docker tools
  hosts: all
  become: true
  become_user: root
  tasks: 
  - name: Install Docker
    ansible.builtin.dnf:
      name:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin
        - docker-compose-plugin
      state: latest
  - name: Set up mirror registry
    ansible.builtin.copy:
      dest: /etc/docker/daemon.json
      src: ./files/daemon.json
  - name: Enable Docker Service
    ansible.builtin.service:
      name: docker
      enabled: true
      state: started
  - name: Add almalinux to the docker group
    ansible.builtin.user:
      append: true
      groups: docker
      name: almalinux
