- name: Add hadoop tmp directory
  ansible.builtin.file:
    path: /opt/hadoop_tmp
    owner: almalinux
    group: almalinux
    state: directory
  become: true
  become_user: root
- name: Add hdfs directory
  ansible.builtin.file:
    path: /opt/hadoop_tmp/hdfs
    state: directory
- name: create namenode
  ansible.builtin.file:
    path: /opt/hadoop_tmp/hdfs/namenode
    state: directory
- name: generate worker file
  ansible.builtin.template:
    src: templates/workers.j2
    dest: hadoop-3.4.1/etc/hadoop/workers
