#cloud-config
package_reboot_if_required: true
package_update: true
package_upgrade: true

bootcmd:
  - [ dnf, config-manager, --set-enabled, crb ]
  - [ dnf, install, -y, epel-release ]

packages:
  - screen
  - tmux
  - nano
  - vim
  - bind-utils
  - net-tools
  - git
  - htop
  - python3-pip
  - python3-virtualenv
  - python3-devel
  - podman
  - ansible

ssh_authorized_keys:
  - ${public_key_openssh}
