#cloud-config
bootcmd:
  - [ dnf, config-manager, --set-enabled, crb ]
  - [ dnf, install, -y, epel-release ]

packages:
  - glibc-langpack-en

runcmd:
  - [ localectl, set-locale, en_GB.UTF-8 ]
  
ssh_authorized_keys:
  - ${public_key_openssh}
