- name: create namenode
  ansible.builtin.file:
    path: /opt/hadoop_tmp/hdfs/namenode
    state: directory
- name: generate worker file
  ansible.builtin.template:
    src: files/workers.j2
    dest: hadoop-3.4.1/etc/hadoop/workers
