- name: Set up minio
  become: true
  become_user: root
  hosts: all
  tasks: 
  - name: Create minio group
    ansible.builtin.group:
      name: minio-user
      state: present
  - name: Create minio user
    ansible.builtin.user:
      append: true
      groups: minio-user
      password: "!"
      state: present
      name: minio-user
  - name: Create private key
    community.crypto.openssl_privatekey:
      path: /root/minio.key
  - name: Create certificate request
    community.crypto.openssl_csr_pipe:
      privatekey_path: /root/minio.key
      common_name: "{{ inventory_hostname }}"
      organization_name: "UCL"
      subject_alt_name:
       - "IP:{{ inventory_hostname }}"
    register: csr
  - name: Create certificate
    community.crypto.x509_certificate:
      path: /root/minio.crt
      csr_content: "{{ csr.csr }}"
      privatekey_path: /root/minio.key
      provider: selfsigned
  - name: Create minio settings directory
    ansible.builtin.file:
      name: "/home/minio-user/.minio"
      state: directory
      owner: minio-user
      group: minio-user
  - name: Create minio settings directory
    ansible.builtin.file:
      name: "/home/minio-user/.minio/certs"
      state: directory
      owner: minio-user
      group: minio-user      
  - name: Create minio client settings directory
    ansible.builtin.file:
      name: "/home/almalinux/.mc"
      state: directory
      owner: almalinux
      group: almalinux
  - name: Create minio client settings directory
    ansible.builtin.file:
      name: "/home/almalinux/.mc/certs"
      state: directory
      owner: almalinux
      group: almalinux
  - name: Copy the certificate to the minio-user directory
    ansible.builtin.copy:
      remote_src: true
      owner: minio-user
      group: minio-user
      mode: "0600"
      src: "/root/minio.crt"
      dest: "/home/minio-user/.minio/certs/public.crt"
  - name: Copy the key to the minio-user directory
    ansible.builtin.copy:
      remote_src: true
      owner: minio-user
      group: minio-user
      mode: "0600"
      src: "/root/minio.key"
      dest: "/home/minio-user/.minio/certs/private.key"
  - name: Copy the certificate to the almalinux mc directory
    ansible.builtin.copy:
      remote_src: true
      owner: almalinux
      group: almalinux
      mode: "0600"
      src: "/root/minio.crt"
      dest: "/home/almalinux/.mc/certs/{{inventory_hostname}}.crt"
  - name: Create minio sub-dir of /data
    ansible.builtin.file:
      path: /data/minio
      owner: minio-user
      group: minio-user
      mode: "0700"
      state: directory
  - name: Get Minio RPM
    ansible.builtin.get_url:
      dest: "/root/minio.rpm"
      url: "https://dl.min.io/server/minio/release/linux-amd64/archive/minio-20240913202602.0.0-1.x86_64.rpm"
  - name: Install Minio RPM
    ansible.builtin.shell: dnf install -y /root/minio.rpm
  - name: Install Minio command-line
    ansible.builtin.get_url:
      dest: /usr/local/bin/mc
      url: "https://dl.min.io/client/mc/release/linux-amd64/mc"
      mode: "0755"
  - name: Set up environment file
    ansible.builtin.template:
      src: files/minio.j2
      dest:  /etc/default/minio
      owner: root
      group: minio-user
      mode: "0640"
  - name: Start Minio
    ansible.builtin.systemd_service:
      name: minio
      state: started
      enabled: true
  - name: Copy minio pass to almalinux directory
    ansible.builtin.copy:
      remote_src: true
      owner: almalinux
      group: almalinux
      mode: "0600"
      src: "/root/miniopass"
      dest: "/home/almalinux/miniopass"