- name: BeeGFS packages
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: Kernel source
    ansible.builtin.dnf:
      name: "kernel-devel"
      state: latest
  - name: BeeGFS Repo
    ansible.builtin.yum_repository:
      baseurl: "https://www.beegfs.io/release/beegfs_7.4.5/dists/rhel9"
      state: present
      gpgkey: "https://www.beegfs.io/release/beegfs_7.4.5/gpg/GPG-KEY-beegfs"
      gpgcheck: true
      name: "BeeGFS"
      description: "BeeGFS repo"
  - name: Install BeeGFs packages
    ansible.builtin.dnf:
      name: 
      - "beegfs-storage"
      - "beegfs-client"
      - "beegfs-utils"
      - "beegfs-helperd"
      - "beegfs-mgmtd"
      - "beegfs-meta"
      state: latest
