- name: Set up firewall
  become: true
  become_user: root
  hosts: all
  tasks: 
  - name: enable ufw
    ansible.builtin.shell: "echo y | ufw enable"
  - name: allow traffic from cluster hosts
    ansible.builtin.shell: "ufw allow from {{ item }}"
    loop: "{{ query('inventory_hostnames', 'all')  }}"
