- name: Install and configure hadoop
  hosts: all
  tasks: 
  - name: Download hadoop
    ansible.builtin.get_url:
      dest: /home/almalinux/hadoop.tar.gz
      url: "https://dlcdn.apache.org/hadoop/common/hadoop-3.4.0/hadoop-3.4.0-src.tar.gz"
  - name: Unpack tgz file
    ansible.builtin.unarchive:
      dest: /home/almalinux/
      remote_src: true
      src: /home/almalinux/hadoop.tar.gz

