- name: Install and configure hadoop
  hosts: all
  tasks: 
  - name: Download hadoop
    ansible.builtin.get_url:
      dest: /home/almalinux/hadoop.tar.gz
      url: "https://dlcdn.apache.org/hadoop/common/hadoop-3.4.0/hadoop-3.4.0.tar.gz"
  - name: Unpack tgz file
    ansible.builtin.unarchive:
      dest: /home/almalinux/
      remote_src: true
      src: /home/almalinux/hadoop.tar.gz
  - name: Set hadoop environment
    ansible.builtin.blockinfile:
      path: /home/almalinux/.bashrc
      block: |
        export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
        export HADOOP_HOME=/home/almalinux/hadoop-3.4.0
        export HADOOP_INSTALL=$HADOOP_HOME
        export YARN_HOME=$HADOOP_HOME
        export PATH=$PATH:$HADOOP_INSTALL/bin
        export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
        export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib"
      state: present


